apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anywork-lp
  annotations:
    cert-manager.io/cluster-issuer: cert-manager
    # nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "www.ginyverse.com"
        - "ginyverse.com"
      secretName: lp-anywaka-tls
  rules:
    - host: ginyverse.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: lp-fe
                port:
                  number: 80
    - host: www.ginyverse.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: lp-fe
                port:
                  number: 80
